##################################################
# file: LoginCMSService_types.py
#
# schema types generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#    /usr/bin/wsdl2py https://wsaahomo.afip.gov.ar/ws/services/LoginCms?WSDL
#
##################################################

import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED

##############################
# targetNamespace
# https://wsaahomo.afip.gov.ar/ws/services/LoginCms
##############################

class ns1:
    targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms"

    class LoginFault_Def(ZSI.TCcompound.ComplexType, TypeDefinition):
        schema = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms"
        type = (schema, "LoginFault")
        def __init__(self, pname, ofwhat=(), attributes=None, extend=False, restrict=False, **kw):
            ns = ns1.LoginFault_Def.schema
            TClist = []
            self.attribute_typecode_dict = attributes or {}
            if extend: TClist += ofwhat
            if restrict: TClist = ofwhat
            ZSI.TCcompound.ComplexType.__init__(self, None, TClist, pname=pname, inorder=0, **kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    return
            Holder.__name__ = "LoginFault_Holder"
            self.pyclass = Holder

    class fault_Dec(ElementDeclaration):
        literal = "fault"
        schema = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms"
        substitutionGroup = None
        def __init__(self, **kw):
            kw["pname"] = ("https://wsaahomo.afip.gov.ar/ws/services/LoginCms","fault")
            kw["aname"] = "_fault"
            if ns1.LoginFault_Def not in ns1.fault_Dec.__bases__:
                bases = list(ns1.fault_Dec.__bases__)
                bases.insert(0, ns1.LoginFault_Def)
                ns1.fault_Dec.__bases__ = tuple(bases)

            ns1.LoginFault_Def.__init__(self, **kw)
            if self.pyclass is not None: self.pyclass.__name__ = "fault_Dec_Holder"

# end class ns1 (tns: https://wsaahomo.afip.gov.ar/ws/services/LoginCms)

##############################
# targetNamespace
# http://wsaa.view.sua.dvadac.desein.afip.gov
##############################

class ns0:
    targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov"

    class loginCms_Dec(ZSI.TCcompound.ComplexType, ElementDeclaration):
        literal = "loginCms"
        schema = "http://wsaa.view.sua.dvadac.desein.afip.gov"
        def __init__(self, **kw):
            ns = ns0.loginCms_Dec.schema
            TClist = [ZSI.TC.String(pname=(ns,"in0"), aname="_in0", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("http://wsaa.view.sua.dvadac.desein.afip.gov","loginCms")
            kw["aname"] = "_loginCms"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self,None,TClist,inorder=0,**kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self._in0 = None
                    return
            Holder.__name__ = "loginCms_Holder"
            self.pyclass = Holder

    class loginCmsResponse_Dec(ZSI.TCcompound.ComplexType, ElementDeclaration):
        literal = "loginCmsResponse"
        schema = "http://wsaa.view.sua.dvadac.desein.afip.gov"
        def __init__(self, **kw):
            ns = ns0.loginCmsResponse_Dec.schema
            TClist = [ZSI.TC.String(pname=(ns,"loginCmsReturn"), aname="_loginCmsReturn", minOccurs=1, maxOccurs=1, nillable=False, typed=False, encoded=kw.get("encoded"))]
            kw["pname"] = ("http://wsaa.view.sua.dvadac.desein.afip.gov","loginCmsResponse")
            kw["aname"] = "_loginCmsResponse"
            self.attribute_typecode_dict = {}
            ZSI.TCcompound.ComplexType.__init__(self,None,TClist,inorder=0,**kw)
            class Holder:
                typecode = self
                def __init__(self):
                    # pyclass
                    self._loginCmsReturn = None
                    return
            Holder.__name__ = "loginCmsResponse_Holder"
            self.pyclass = Holder

# end class ns0 (tns: http://wsaa.view.sua.dvadac.desein.afip.gov)
